### ISSUE TITLE
app.use and partial URL checking

### ISSUE THREAD

**Issue by AhmedSafi97** [GSG-G9/OK-Book.Library#25]
https://github.com/GSG-G9/OK-Book.Library/blob/b9881cae8bb73cd9413f0c0247272af188e558b1/src/app.js#L19

`app.use` fires for all methods and all endpoints if it's not provided with a path, but be careful when giving it a path, since it makes a partial match with the request's url. How is that? 

Take this example: 
```js
app.use("/api", router)
```
This will fire for whatever request that its url starts with `/api`, it will match all of the following: `/api/jobs`, `/api/news` ...etc.

Therefore, in your case it will match all urls since whatever url starts with `/` it will match with it, so it's no different from `app.use(router)`

Read more about [`app.use`](http://expressjs.com/en/5x/api.html#app.use)

Also, if you want to fire a middleware for all methods but make a full match(not partial match like `app.use`), see this one [`app.all`](http://expressjs.com/en/5x/api.html#app.all)

**Comment by Osama-you** [comment]
Doesn't that solve the problem؟!!

[https://github.com/GSG-G9/OK-Book.Library/blob/main/src/router/index.js](https://github.com/GSG-G9/OK-Book.Library/blob/main/src/router/index.js)
```js
const router = require('express').Router();
const { notFoundRoute } = require('../controllers/notFound');
const api = require('./api');
const home = require('./home');

router.use('/api/v1', api);
router.use('/', home);
router.use('/notFound', notFoundRoute);

module.exports = router;
```

**Comment by AhmedSafi97** [comment]
My point is `app.use("/", router)` will do the same of `app.use(router)`. I hope it's clear now after the morning session.

**Comment by Osama-you** [comment]
yup, we get it. thx
